"""models changed

Revision ID: 090eae421d00
Revises: 1cdec64ad4dd
Create Date: 2026-08-24 10:54:52.649308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '090eae421d00'
down_revision: Union[str, Sequence[str], None] = '1cdec64ad4dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embedded_text_document', sa.Column('document_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'embedded_text_document', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('runs_config_id_fkey'), 'runs', type_='foreignkey')
    op.drop_constraint(op.f('runs_document_id_fkey'), 'runs', type_='foreignkey')
    op.create_foreign_key(None, 'runs', 'pipeline_configs', ['config_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'runs', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'runs', type_='foreignkey')
    op.drop_constraint(None, 'runs', type_='foreignkey')
    op.create_foreign_key(op.f('runs_document_id_fkey'), 'runs', 'documents', ['document_id'], ['id'])
    op.create_foreign_key(op.f('runs_config_id_fkey'), 'runs', 'pipeline_configs', ['config_id'], ['id'])
    op.drop_constraint(None, 'embedded_text_document', type_='foreignkey')
    op.drop_column('embedded_text_document', 'document_id')
    # ### end Alembic commands ###
