"""updated models

Revision ID: 4e2d622a0499
Revises: 090eae421d00
Create Date: 2026-08-24 12:30:08.833093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e2d622a0499'
down_revision: Union[str, Sequence[str], None] = '090eae421d00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('embedded_text_document', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('embedded_text_document_document_id_fkey'), 'embedded_text_document', type_='foreignkey')
    op.drop_column('embedded_text_document', 'document_id')
    op.drop_column('embedded_text_document', 'file_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embedded_text_document', sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('embedded_text_document', sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('embedded_text_document_document_id_fkey'), 'embedded_text_document', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.alter_column('embedded_text_document', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
