"""changed file name

Revision ID: b69034854ed0
Revises: d88ce1d98d6c
Create Date: 2026-08-13 10:51:24.842467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b69034854ed0'
down_revision: Union[str, Sequence[str], None] = 'd88ce1d98d6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_name', sa.String(), nullable=False))
    op.drop_column('documents', 'filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('documents', 'file_name')
    # ### end Alembic commands ###
