"""changed file storage

Revision ID: d88ce1d98d6c
Revises: a7d249cad139
Create Date: 2026-08-13 09:52:03.461250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd88ce1d98d6c'
down_revision: Union[str, Sequence[str], None] = 'a7d249cad139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_url', sa.String(), nullable=False))
    op.drop_column('documents', 'cloudinary_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('cloudinary_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('documents', 'file_url')
    # ### end Alembic commands ###
